default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: essayist_development

test:
  <<: *default
  database: essayist_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
